# Configuration du framework

log_level: INFO
monitoring_interval: 3600

web_scanner:
  timeout: 30
  max_depth: 3

network:
  interface: eth0
  capture_timeout: 300

malware:
  max_file_size: 10485760

threat_intel:
  api_keys:
    virustotal: your_key_here
    alienvault: your_key_here

apt:
  detection_threshold: 0.8
  window_size: 1000

reporting:
  output_dir: reports
  format: pdf
